more hints

diff --git a/batchload b/batchload
--- a/batchload
+++ b/batchload
@@ -52,7 +52,7 @@ fi
 
 if ! command -v voms-proxy-init > /dev/null
 then 
-    echo "voms-proxy-init not found, quitting..." 1>&2
+    echo "voms-proxy-init not found (did you setup dq2?), quitting..." 1>&2
     exit 1
 fi 
 voms-proxy-init -voms atlas -out local_cert
