more docs

diff --git a/batchload b/batchload
--- a/batchload
+++ b/batchload
@@ -1,17 +1,48 @@
 #!/usr/bin/env bash
 
+usage() {
+    cat <<EOF
+usage: ${0##*/} [--help] [containers...]
+EOF
+}
+doc() { 
+    usage
+    echo 
+    cat <<EOF
+Creates and submits dq2-get jobs to PBS. One job will be created for 
+each container listed. 
+
+With no containers, will read from a pipe (if one exists). 
+
+The datasets will be downloaded to your working directory. 
+
+NOTE: You should only run this in an empty directory where there is room 
+to download lots of data! The messy nature of submitting to PBS means your 
+working directory may become littered with shell scripts and batch output. 
+
+This is supposed to be stupidly easy to use. If you have questions, ask Dan. 
+Dan likes to help. 
+EOF
+}
 script_name=dq2batch.sh
 
-if [ $# == 0 ] 
+if [[ $# == 0 ]]
     then 
-    files=$(cat)
+    if [[ ! -t 0 ]]
+    then 
+	files=$(cat)
+    else
+	usage
+	echo "no containers, quitting..." 1>&2
+	exit 1
+    fi
 else 
     for arg in $@
     do 
 	case $arg in 
 	    --help )
-		echo "usage: ${0##*/} <container list>"
-		return 1 ;;
+		doc
+		exit 1 ;;
 	    *)
 		files+=${arg}" " ;;
 	esac
@@ -20,11 +51,15 @@ fi
 
 if ! command -v voms-proxy-init > /dev/null
 then 
-    echo "need to setup voms-proxy-init" 1>&2
-    return 1
+    echo "voms-proxy-init not found, quitting..." 1>&2
+    exit 1
 fi 
 voms-proxy-init -voms atlas -out local_cert
-
+if [[ $? ]] 
+then 
+    echo 'voms failure, quitting...' 1>&2
+    exit 1
+fi
 
 cat >| $script_name <<EOF
 shopt -s expand_aliases
